name: Java CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew clean build --no-daemon

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew test --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: build/reports/tests/test
          retention-days: 7

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - run: ./gradlew integrationTest --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: integration-test-reports
          path: build/reports/tests/integrationTest
          retention-days: 7
